### ISSUE TITLE
Error when opening dds file

### ISSUE THREAD

**Issue by xrSimpAI** [0xC0000054/pdn-ddsfiletype-plus#18]
I got this error when trying to open textures from the game Stalker Call of Pripyat: 
[ui.zip](https://github.com/user-attachments/files/16272871/ui.zip)

The explorer preview shows these textures:
![image](https://github.com/user-attachments/assets/dd1ee068-6423-41e2-bc2b-b272fedecc40)

I would like to understand what is wrong with them.
```
Exception:

System.FormatException: The DDS file is invalid.
   at DdsFileTypePlus.DdsNative.Load(Stream stream, DDSLoadInfo& info) in D:\Dev_projects\DdsFileTypePlus\src\DdsNative.cs:line 57
   at DdsFileTypePlus.DdsReader.Load(Stream input, IServiceProvider services) in D:\Dev_projects\DdsFileTypePlus\src\DdsReader.cs:line 30
   at PaintDotNet.FileType.Load(Stream input) in D:\src\pdn\src_5_0_x\Data\FileType.cs:line 491
   at PaintDotNet.Data.FileTypeProxy.OnLoad(Stream input) in D:\src\pdn\src_5_0_x\PaintDotNet\Data\FileTypeProxy.cs:line 60
   at PaintDotNet.FileType.Load(Stream input) in D:\src\pdn\src_5_0_x\Data\FileType.cs:line 491
   at PaintDotNet.Functional.Func.Eval[T1,TRet](Func`2 f, T1 arg1) in D:\src\pdn\src_5_0_x\Fundamentals\Functional\Func.cs:line 60

Diagnostics:

Application                                          paint.net версия 5.0.13 (Stable 5.13.8830.42291)
Build Date                                           5 марта 2024 г.
Install type                                         Classic
```

**Comment by rickbrew** [comment]
Possibly related to #14 and/or #16 ? STALKER DDS files seem to cause all sorts of problems

**Comment by 0xC0000054** [comment]
Those files are TGA, not DDS.

**Comment by xrSimpAI** [comment]
I wonder how the **D3DX** texture loader worked, that it could load images in `.png`, `.tga` under the guise of `.dds` and various invalid `.dds` formats🤔

**Comment by 0xC0000054** [comment]
It is probably checking the file signatures, instead of relying on the file extension.
